name: Code Lint & Build Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint_and_build:
    name: Run ESLint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        id: eslint_run
        continue-on-error: true
        run: |
          echo "### ESLint Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          pnpm run lint --no-color | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check Status
        if: steps.eslint_run.outcome == 'failure'
        run: exit 1

      - name: Run Build
        id: build_run
        continue-on-error: true
        run: |
          echo "### Dist File List" >> $GITHUB_STEP_SUMMARY
          echo "$(find dist -type f | wc -l) Files:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          pnpm run build
          npx -y tree-node-cli dist --sizes --all-files --dirs-first --trailing-slash | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check Status
        if: steps.build_run.outcome == 'failure'
        run: exit 1
